### ISSUE TITLE
General tracking issue

### ISSUE THREAD

**Issue by Ben-PH** [CargoLens/cargo-lens-ws#1]
- [x] create dev branch
- [x] create CI
  - [x] PR to main
  - [x] PR to dev
- [ ] sketch out design
- [ ] develop initial feature roadmap
- [ ] determine milestones
