### ISSUE TITLE
Feature: Code-review checklist

### ISSUE THREAD

**Issue by Ben-PH** [CargoLens/cargo-lens-ws#4]
#11 

First feature. Idea being: before asking for a review, go through these items with cargo-lens, ensuring that the code is in a good place for review, and relevant context has been prompted for.

- compiles (fail -> feature to handle compile error scenario). for now, compile fail -> roadmap message, user-ack, revert menu
- clear of warnings
- test-failures explanation
- prompt to consider more/less tests
- select lints to ignore
- lint warnings/errors clear (fail -> feature to manage lint warn/errs)
- select files/sections that need careful attention
- prompt for "parts of code base that, please, don't review yet" selection
- common request specifics
- code-base annotations

#### General plan

- [x] stub in the list
- [x] add basic functionality/interactivity (to be expanded
- [ ] connect specific steps to supporting code (e.g. "code checks without warnings" validates non-clippy warnings are clear)
- [ ] can add overall comment
- [ ] can add file-specific annotations
- [ ] can add line-range-specific annotations
- [ ] at some point, hard-code something to demo what the complete feature might look like

### Supporting tasks

- [ ] make it configurable to include common CI things in addition (e.g. rust-fmt is good)
- [ ] Runs runs some cargo ops in order (build, clippy, test) Can cross tabs to show process process.
- [ ] capture cargo output
- [ ] Parse cargo output
- [ ] organise cargo output
- [ ] use cargo output 
- [ ] hide/show toggle of clippy lints
